version: "3"

services:
  webserver:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "./nginx/html:/usr/share/nginx/html"
      - "./nginx/conf.d:/etc/nginx/conf.d"
  api:
    container_name: api
    build: ./fastapi
    ports:
      - "8000:8000"
    volumes:
      - "./fastapi:/app"
  mlflow:
    container_name: mlflow 
    build: ./mlflow
    ports:
      -  "5000:5000"
    volumes:
      - "./mlflow:/mlflow"
      - "./model_update:/model_update"
    command: mlflow server 
             --backend-store-uri sqlite:///mydb.sqlite
             --default-artifact-root file:/model_update/mlruns
             --host 0.0.0.0 --port 5000 
    restart: always
  model_update:
    container_name: model_update
    build: ./model_update
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment: 
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all
    # ports:
    #   - "5000:5000"
    volumes:
      - "./model_update:/model_update"
    command: python train.py
    
    